Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import math 																			    def esPrimo(n):																			     if n<2:																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return True
SyntaxError: invalid syntax
>>> import math 																			    def esPrimo(n):																			     if n<2:																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i) 																			    																					     seriePrimo(100000)
SyntaxError: invalid syntax
>>> def Primo(n):																			     if n<2:																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i)
SyntaxError: invalid syntax
>>>  def Primo(n):																			     if (n<2):																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i)
 
SyntaxError: unexpected indent
>>>  def Primo(n):																			     if (n<2):																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i)
 
SyntaxError: unexpected indent
>>> def Primo(n):																			     if (n<2):																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i)
SyntaxError: invalid syntax
>>> def Primo(n):																			     if(n<2):																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i)
SyntaxError: invalid syntax
>>> def Primo(n):																			      if(n<2):																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i)
SyntaxError: invalid syntax
>>> def Primo(n):																			    if(n<2):																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i)
SyntaxError: invalid syntax
>>> def Primo(n):																			       if(n<2):																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i)
SyntaxError: invalid syntax
>>> def Primo(n):																			     if (n<2):																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i)
SyntaxError: invalid syntax
>>> def Primo(n):																			        if (n<2):																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i)
SyntaxError: invalid syntax
>>> def Primo(n):																			      																					      if (n<2):																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i)

SyntaxError: invalid syntax
SyntaxError: invalid syntax
>>> 
>>> 
>>> def Primo(n):																			      																					      if (n<2):																					return False 																			     for x in range(2,int(math.srqt(n))+1):																     if(n%x==0)																				        return False                                                                                                                                                         return True 																																																													     def seriePrimo(numPrimo):																		      c=0  																				      i=0 																				      while c<numPrimo:  																		         i+=1 																					 if esPrimo(i): 																			    c+=1 																				    print (i)

SyntaxError: invalid syntax
